### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by felix28** [robertvazan/sourceafis-java#1]
Hi Robert,

Is it possible that this source code can work in Android?

By the way, in FingerPrintContext class. I always received an error in radius, majority and borderDist.

It seems these three does not exists in Voting Parameter Class as a method but as a properties.

**Comment by robertvazan** [comment]
It should work on Android just like any other Java library. Why aren't you using the Maven artifacts? What errors do you get exactly?

**Comment by felix28** [comment]
I received an error like radius is not a method. Something like that.

Anyways, I am now using the JAR file not the source code. I try to use it in Android.

Currently, I don't have problems in running it.

**Comment by robertvazan** [comment]
The missing method might be caused by lombok annotations not getting compiled. As I see it, the problem has been fully resolved.
