### ISSUE TITLE
 java.lang.VerifyError: com/machinezoo/sourceafis/TemplateBuilder

### ISSUE THREAD

**Issue by SamGeek** [robertvazan/sourceafis-java#10]
Here is my stacktrace

12-17 16:16:47.548 4857-4857/com.fgtit.fingermap E/dalvikvm: Could not find class 'com.machinezoo.sourceafis.-$$Lambda$FingerprintTransparency$bxEfwQYwk7xURQd0FvRXP0V_KSg', referenced from method com.machinezoo.sourceafis.FingerprintTransparency.json
12-17 16:16:47.554 4857-4857/com.fgtit.fingermap E/dalvikvm: Could not find class 'com.machinezoo.sourceafis.-$$Lambda$Ybta_3GA0aExx2iuGeU-MoqWUyc', referenced from method com.machinezoo.sourceafis.FingerprintTransparency.logBooleanMap
12-17 16:16:47.555 4857-4857/com.fgtit.fingermap E/dalvikvm: Could not find class 'com.machinezoo.sourceafis.-$$Lambda$vTn_9J5XoH3lgRilx-n-zhp0WDo', referenced from method com.machinezoo.sourceafis.FingerprintTransparency.logDoubleMap
12-17 16:16:47.557 4857-4857/com.fgtit.fingermap E/dalvikvm: Could not find class 'com.machinezoo.sourceafis.-$$Lambda$O3nxvKO69gAbI9j-1qVeVoGSTFE', referenced from method com.machinezoo.sourceafis.FingerprintTransparency.logHistogram
12-17 16:16:47.558 4857-4857/com.fgtit.fingermap E/dalvikvm: Could not find class 'com.machinezoo.sourceafis.-$$Lambda$FingerprintTransparency$Nfc7TLQ3rE6aLE0vpb4VJPfFdZA', referenced from method com.machinezoo.sourceafis.FingerprintTransparency.logMinutiae
12-17 16:16:47.560 4857-4857/com.fgtit.fingermap E/dalvikvm: Could not find class 'com.machinezoo.sourceafis.-$$Lambda$1mpxgaVXJYYhua_urH6RebY05Is', referenced from method com.machinezoo.sourceafis.FingerprintTransparency.logPointMap
12-17 16:16:47.563 4857-4857/com.fgtit.fingermap E/dalvikvm: Could not find class 'com.machinezoo.sourceafis.-$$Lambda$FingerprintTransparency$FcZVeRGwvHWAwjyBWdB2jEErK4I', referenced from method com.machinezoo.sourceafis.FingerprintTransparency.logSkeleton
12-17 16:16:47.564 4857-4857/com.fgtit.fingermap E/dalvikvm: Could not find class 'com.machinezoo.sourceafis.-$$Lambda$FingerprintTransparency$zY92akZXEZd0jUjbyt17TSukveM', referenced from method com.machinezoo.sourceafis.FingerprintTransparency.logBestMatch
12-17 16:16:47.565 4857-4857/com.fgtit.fingermap E/dalvikvm: Could not find class 'com.machinezoo.sourceafis.-$$Lambda$FingerprintTransparency$KJ-QQXxBTwSUtCLLvWd4FO4s900', referenced from method com.machinezoo.sourceafis.FingerprintTransparency.logBlockMap
12-17 16:16:47.566 4857-4857/com.fgtit.fingermap E/dalvikvm: Could not find class 'com.machinezoo.sourceafis.-$$Lambda$FingerprintTransparency$YNHJ3S8uPX-COtLfSiWzc_DH_HI', referenced from method com.machinezoo.sourceafis.FingerprintTransparency.logEdgeHash
12-17 16:16:47.568 4857-4857/com.fgtit.fingermap E/dalvikvm: Could not find class 'com.machinezoo.sourceafis.-$$Lambda$FingerprintTransparency$m189AtGZxTeszYUZH1Ar3At_Gew', referenced from method com.machinezoo.sourceafis.FingerprintTransparency.logEdgeTable
12-17 16:16:47.569 4857-4857/com.fgtit.fingermap E/dalvikvm: Could not find class 'com.machinezoo.sourceafis.-$$Lambda$FingerprintTransparency$ePYS0vZ4s7XzYQ2G2QPaX-F2B5I', referenced from method com.machinezoo.sourceafis.FingerprintTransparency.logIsoMetadata
12-17 16:16:47.570 4857-4857/com.fgtit.fingermap E/dalvikvm: Could not find class 'com.machinezoo.sourceafis.-$$Lambda$FingerprintTransparency$8sgZdxSLzU0buCiYxt5fOlePWNk', referenced from method com.machinezoo.sourceafis.FingerprintTransparency.logPairing
12-17 16:16:47.571 4857-4857/com.fgtit.fingermap E/dalvikvm: Could not find class 'com.machinezoo.sourceafis.-$$Lambda$FingerprintTransparency$8DXMiwcgakNE2z6D9vhj4ehnDk8', referenced from method com.machinezoo.sourceafis.FingerprintTransparency.logRootPairs
12-17 16:16:47.572 4857-4857/com.fgtit.fingermap E/dalvikvm: Could not find class 'com.machinezoo.sourceafis.-$$Lambda$FingerprintTransparency$PpB6BUgvDKB7adncP36O5kom69M', referenced from method com.machinezoo.sourceafis.FingerprintTransparency.logScore
12-17 16:16:47.595 4857-4857/com.fgtit.fingermap E/dalvikvm: Could not find class 'java.util.function.Function[]', referenced from method com.machinezoo.sourceafis.TemplateBuilder.decodeImage
12-17 16:16:47.595 4857-4857/com.fgtit.fingermap E/dalvikvm: Could not find class 'com.machinezoo.sourceafis.-$$Lambda$TemplateBuilder$Dv2GmpbkbkWYmWfhRICjnadOihE', referenced from method com.machinezoo.sourceafis.TemplateBuilder.decodeSafely
12-17 16:16:47.602 4857-4857/com.fgtit.fingermap E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fgtit.fingermap, PID: 4857
    java.lang.VerifyError: com/machinezoo/sourceafis/TemplateBuilder
        at com.machinezoo.sourceafis.FingerprintTemplate.create(FingerprintTemplate.java:95)

Can you give a help please?

**Comment by robertvazan** [comment]
You need Android API level 24+ to have any chance to run SourceAFIS on Android.

Note that even with API level 24+, image decoding doesn't work on Android, because Android lacks ImageIO class. You will have to recompile from sources and replace ImageIO code with equivalent Bitmap code.

**Comment by SamGeek** [comment]
Ok understood. Thanks
