### ISSUE TITLE
Large scale database

### ISSUE THREAD

**Issue by mostafaebrahimi** [robertvazan/sourceafis-java#13]
What's the best way to use `sourceafis` for large scale databases?
I want to authenticate users login to system using their fingerprint.
do you have any idea ?

**Comment by robertvazan** [comment]
That's a large topic. I cannot just answer it here. I will keep this issue open as a reminder to write an article about it.

**Comment by robertvazan** [comment]
All templates must be loaded in RAM and deserialized into FingerprintTemplate objects for matching to be fast. I cannot say more here.

**Comment by mostafaebrahimi** [comment]
but I think this is not an efficient way!
because for 100,000 users we have to handle about 60MB data compare. 
Do have know another idea or platform to store and compare?

**Comment by lucaspcamargo** [comment]
I use LMDB for that. It's neat in the sense that all the fingerprints can be read quickly and the index is fast. But yeah, there is no escaping keeping the processed templates in RAM for fast matching performance. One could try to modify the codebase for having flat templates that can also be memory-mapped, but that is sure to be a pain in Java.

**Comment by mostafaebrahimi** [comment]
@lucaspcamargo  Thanks for your response buddy 
I try to load data in memory and that solved my problem.(using a simple array list and comparing method for 1:n)

**Comment by AlekseyMalyshev** [comment]
> because for 100,000 users we have to handle about 60MB data compare.

Did you mean - Mb or Gb? 60 Mb is not such a large amount of data? It looks more like 60Gb per 100,000 users to me.

**Comment by seuntech** [comment]
> > because for 100,000 users we have to handle about 60MB data compare.
> 
> Did you mean - Mb or Gb? 60 Mb is not such a large amount of data? It looks more like 60Gb per 100,000 users to me.

MB

**Comment by robertvazan** [comment]
Memory usage benchmarks for templates are now available:

https://sourceafis.machinezoo.com/cli

The general topic of using SourceAFIS on large databases is too broad for one issue. Please open separate issues to request specific documentation.
