### ISSUE TITLE
I can't turn off the fingerprintreader 

### ISSUE THREAD

**Issue by davdavcoco** [robertvazan/sourceafis-java#14]
I have button with onclick, so it trigger the fingerprint scan and it work 
basically like
btncheck.setOnClickListener(new View.OnClickListener() {
    if(CheckExistEmployee())
    {
       fingerprint = new Fingerprint();
       fingerprint.scan(AttendanceSaveActivity.this, printHandler, null);
    }
} );

but i try to turnoff the reader when the activity closed so i put fingerprint.turnOffReader() in onDestroy Function. But its not work

@Override
public void onDestroy()
{
      fingerprint.turnOffReader();
      super.onDestroy()
}

did i do something wrong in this ?

**Comment by robertvazan** [comment]
This is unrelated to SourceAFIS.
