### ISSUE TITLE
Unable to match images generated from Swipe and touch FP Scanners

### ISSUE THREAD

**Issue by AWaheed-124** [robertvazan/sourceafis-java#15]
Hello, I am using Windows Biometric Framework to capture Fingerprint data and generate a .bmp image. This image is used by SourceAFIS Matcher to match with templates. 
When i generate image from a swipe scanner and try to match it against a template generated from same finger image taken from touch scanner, it always returns unmatched. Similar behavior is produced vice versa. 
What can be done to overcome this?

**Comment by robertvazan** [comment]
Unfortunately, SourceAFIS is designed for 2D contact sensors, so it probably wouldn't work. But to be sure, check that you have set the right DPI for both probe and candidate images. Other than that, the only option is to try different swipe sensor that can reconstruct a more accurate 2D image.

**Comment by AWaheed-124** [comment]
Hello, SourceAFIS is working perfect with images from similar scanners (Swipe->Swipe or Touch->Touch). But when I try to use image from one to match with other it does not work.

**Comment by robertvazan** [comment]
That's a pretty sure sign of DPI issues. Measure minutia distances in Gimp or other image editor and calculate and compare the result with DPI you think the sensors have.
