### ISSUE TITLE
About rotation invariance

### ISSUE THREAD

**Issue by kpoman** [robertvazan/sourceafis-java#16]
Hello Robert, I see you specify that "SourceAFIS is a rotation-invariant and translation-invariant algorithm.". However I am capturing a probe then trying to identify to the same finger with slight rotations (like ~20 degrees) and the score goes below threashold. Is there an option to activate the invariance for rotation and translation ? Testing on 3.8.1 Java version.

**Comment by kpoman** [comment]
Oh I see static final double maxAngleError = Math.toRadians(10); ... Is this the setting I need to better tolerate rotations ?

**Comment by robertvazan** [comment]
SourceAFIS algorithm will match fingerprints with any relative rotation. The parameter you found specifies maximum angle error in local minutia direction, which is completely unrelated to global rotation. There must be something else that is causing the drop in score. Does your sensor have the same DPI in X and Y directions? Is it big enough to produce sufficient overlap between two scans?

**Comment by kpoman** [comment]
> SourceAFIS algorithm will match fingerprints with any relative rotation. The parameter you found specifies maximum angle error in local minutia direction, which is completely unrelated to global rotation. There must be something else that is causing the drop in score. Does your sensor have the same DPI in X and Y directions? Is it big enough to produce sufficient overlap between two scans?

Robert, I'm gonna double-check as the templates are being generated via NIST nbis (xyt) and maybe I screwed something on the angle conversion to your own format. Is there any way to build a debug image with the image and the template set for it (even if I am forcing the template to be the one I calculated with another lib) ?

**Comment by robertvazan** [comment]
It's currently undocumented, but it works:

https://github.com/robertvazan/sourceafis-visualization-java

You likely need `TransparencyGallery.shuffledMinutiae()`. Look at `TransparencyGalleryTest`.

**Comment by robertvazan** [comment]
I forgot that you have imported templates, so `TransparencyGallery` won't do for you.

You need something like this:

```java
Template parsed = Template.parse(fp.toByteArray());
byte[] visualization = new TransparencyImage(parsed.size)
	.image(image)
	.add(TransparencyMarkers.markTemplate(parsed))
	.bytes()
```

Then save `visualization` as an SVG file.

**Comment by kpoman** [comment]
Robert, I suppose when you create Template, it is a FingerprintTemplate, right ? Because I dont have that class available !
Thanks !

**Comment by robertvazan** [comment]
If you use the maven artifact, you will get all the dependencies:

https://search.maven.org/artifact/com.machinezoo.sourceafis/sourceafis-visualization/0.4.1/jar

**Comment by kpoman** [comment]
I do already have a FingerprintTemplate object (i.e. a string containing {"version": "3.8.1", "minutiae": [{"x": 58, "y": 241, "direction": 3.9269908169872414, "type": "bifurcation"}, {"x": .....) which I built this way:

```
    def __get_vendor_minutiae(self, rec):
        # we must convert our minutia object to SourceAFIS format which is xml
        print('_get_vendor_minutiae')
        obj = {'version':'3.8.1', 'minutiae':[]}
        minutiae = rec['minutiae']
        for m in minutiae:
            minutia = {}
            minutia['x'] = m['x']
            minutia['y'] = m['y']
            minutia['direction'] = (m['a']/360.)*2*math.pi
            minutia['type'] = 'bifurcation' if m['t']==0 else 'ending'
            obj['minutiae'].append(minutia)
        json_obj = json.dumps(obj)
        s = gzip.compress(json_obj.encode('utf-8'))
        template = FingerprintTemplate(s)
        return template
```
(btw I am using SourceAfis from Python via jpype).
Unfortunately it doesnt have a size attribute. Is Template a similar type as FingerprintTemplate or do I have to create a Template bu doing the same I did for FingerprintTemplate (i.e. append minutia then json.dump then gzip) ?

Thank you !

**Comment by robertvazan** [comment]
Image size is informative. You can leave it zeroed.

**Comment by kpoman** [comment]
Ok I think I got a result, I got something saved on disk with an svg:
`
<svg version="1.1" viewBox="-0.0 -0.0 0.0 0.0" xmlns="http://www.w3.org/2000/svg"><image width="0.0" height="0.0" href="data:image/jpeg;base64,/9j/4AAQSkZJRgABAgAAAQABAAD/2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDA...... ...... ....... LexuYZtFLcRs52Kv0PINezwQR20KRRII40GFUdAKcEAJIzycmgCu+m20t0l08Km4Vdu/HOPQ+tWulNYEgYO3mnUAIBimrHsJIJwT0PQfSnEjIBHJ6cUtADCWLjGAB97I6/Sn0UUAFFJnmloAKarbiRg8HGTTqKACiiigD//2Q=="/><g transform="translate(38.5 294.5) rotate(213.0)"><circle cx="0.0" cy="0.0" r="3.5" fill="none" stroke="green"/><line x1="3.5" y1="0.0" x2="10.0" y2="0.0" stroke="green"/></g><g transform="translate(46.5 273.5) rotate(213.0)"><circle cx="0.0" cy="0.0" r="3.5" fill="none" stroke="green"/><line x1="3.5" y1="0.0" x2="10.0" y2="0.0" stroke="green"/></g> ....... ........ ........ <g transform="translate(266.5 330.5) rotate(304.00000000000006)"><circle cx="0.0" cy="0.0" r="3.5" fill="none" stroke="blue"/><line x1="3.5" y1="0.0" x2="10.0" y2="0.0" stroke="blue"/></g></svg>`

I'm trying to view the svg from many tools here with no luck, nor Chrome nor Linux Mint image viewer nor anything does open it. Bizarre !

**Comment by robertvazan** [comment]
Aha. Image size is optional for matching, but it will screw up visualization... Give the template some estimated size if you don't know the real image size.

**Comment by kpoman** [comment]
Cool I finally could dump it ! It is pretty weird:
https://pasteboard.co/IM7qjTi.png
I dont get why it got so screwed. Maybe some endianness error (like image upside down) ?

**Comment by robertvazan** [comment]
Minutia positions are right. You have got angles wrong. Check your conversion code.
