### ISSUE TITLE
accuracy and time ?

### ISSUE THREAD

**Issue by mv2050arshad** [robertvazan/sourceafis-java#17]
Hi 
first of all i want to appreciated you to share your nice project.

i want to know how much is your estimate for accuracy rate and searching time in 1:N identification request ?

**Comment by robertvazan** [comment]
I should post a more comprehensive report about this on the website, so I will keep this issue open as a reminder. Meantime I can only give you approximate values. Matching speed is currently about 12,500 fp/s per core on large high-quality fingerprints. Accuracy is on the lower end compared to commercial algorithms, but it is good enough for small databases (up to 10,000 fingerprints) and with 2-finger matching it is also good enough for larger projects. Small sensor applications regularly run into accuracy issues though.

**Comment by kpoman** [comment]
Hello Robert,
I can't reach the 12,500 fp/s. I slightly modified the FingerprintMatcherTest.java to loop 1000 times:

```
private void matching(FingerprintTemplate probe, FingerprintTemplate candidate) {
            double score = 0;
            for (int i=0; i<1000; i++) {
		score = new FingerprintMatcher()
			.index(probe)
			.match(candidate);
            }
            assertThat(score, greaterThan(40.0));
	}

```
and get the test run in

> Running com.machinezoo.sourceafis.FingerprintMatcherTest
> Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 17.782 sec

about 17ms per match ! Am I doing something wrong ? (Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz)

**Comment by robertvazan** [comment]
@kpoman The 12,500 fp/s figure applies to 1:N matching, not 1:1 as in your example. If you are wondering what's the difference between 1:1 and 1:N, carefully read the 1:N section in the tutorial:

https://sourceafis.machinezoo.com/java

**Comment by kpoman** [comment]
@robertvazan thank you ! I will try it that way !

**Comment by robertvazan** [comment]
Accuracy and speed benchmarks are now posted on the website:

https://sourceafis.machinezoo.com/cli
