### ISSUE TITLE
Struggling to get json from FingerprintTransparency

### ISSUE THREAD

**Issue by moleisking** [robertvazan/sourceafis-java#18]
I am trying to extract the "shuffled-minutiae" json information as of your example. I can't seem to find details on what is the "content" and how to turn  "content" into a string that I can then extract data from. It is byte format, so what is the process to convert it into string format. Is it gzip -> base64 -> string ...? I have other code where i played with this but could not work it out.
```
class TransparencyContents extends FingerprintTransparency {
        @Override
        protected void capture(String keyword, Map<String, Supplier<byte[]>> data) {
            for (String suffix : data.keySet()) {
                byte[] content = data.get(suffix).get();
                // System.out.printf("%,9d B %-6s %s\n", content.length, suffix, keyword);
                if (suffix.equals(".json") && keyword.equals("shuffled-minutiae")) {
                    System.out.println(keyword);
                    System.out.println(suffix);
                    System.out.println(content.length + "B");
                    System.out.println(content);        
                }
            }
        }
    }
```

**Comment by robertvazan** [comment]
If you are using Java, you might have more luck with [sourceafis-transparency-java](https://github.com/robertvazan/sourceafis-transparency-java), which does all the parsing for you although it is currently undocumented.

If you stick with sourceafis-java alone, read the docs carefully. When suffix is `".json"`, then the `byte[]` array is JSON-encoded. Convert the `byte[]` to `String` via UTF-8 encoding and then dump it. You will see the JSON document. Then just use some JSON parsing library.

**Comment by robertvazan** [comment]
BTW, the shuffled minutiae output is identical to the actual template (except that the template is also gzip-compressed), so you don't really need transparency to obtain it.

**Comment by moleisking** [comment]
Hi Thanks, code seems to work great!
class TransparencyContents extends FingerprintTransparency {
        @Override
        protected void capture(String keyword, Map<String, Supplier<byte[]>> data) {
            for (String suffix : data.keySet()) {
                byte[] content = data.get(suffix).get();
                if (suffix.equals(".json") && keyword.equals("shuffled-minutiae")) {                                      
                    String json = new String(content, StandardCharsets.UTF_8);
                    System.out.println(json);
                   
                }
            }
        }
    }
