### ISSUE TITLE
Java 1.7 compatible version

### ISSUE THREAD

**Issue by jessejohnson** [robertvazan/sourceafis-java#2]
Hey there,
your library is probably the best I've come across after nearly a week of searching for a way to transform fingerprint images into templates for matching.
Unfortunately, the Android device I'm working with does not allow me to use certain Java 8 features. Do you have an older version of this library I can fallback on?
All I've seen so far are `2.x` alpha releases...

**Comment by robertvazan** [comment]
SourceAFIS uses Java 8 APIs, especially streams and other lambda-related APIs. It won't compile under Java 7. Due to the widespread use and utility of lambdas, porting SourceAFIS to Java 7 would be unreasonable. Your best bet is `gradle-retrolamba` or Android Studio 3.0.
