### ISSUE TITLE
Caching fingerprint templates

### ISSUE THREAD

**Issue by edolo595** [robertvazan/sourceafis-java#20]
Hi, I have a question, how can I deserialize the templates in the zip file.
i used this:

### FingerprintTemplate template = new FingerprintTemplate(serialized);

but I get this error, could you help me.

![Captur1111a](https://user-images.githubusercontent.com/58313938/74365988-c1ca9880-4d94-11ea-9056-e978ca16f7f2.PNG)

**Comment by robertvazan** [comment]
Can you post the code that generated the template? Does it work when you serialize and immediately deserialize it?

**Comment by edolo595** [comment]
try (
        OutputStream stream = new FileOutputStream("transparency1.zip");
        FingerprintTransparency transparency = FingerprintTransparency.zip(stream)
        ) {
            byte[] image = Files.readAllBytes(Paths.get("img.jpg"));
        FingerprintTemplate probe;
        probe = new FingerprintTemplate().dpi(500).create(image);
        
        
        }

**Comment by edolo595** [comment]
save this:

![obtenido](https://user-images.githubusercontent.com/58313938/74377325-50e1ab80-4da9-11ea-8751-58afda804a0f.PNG)

**Comment by robertvazan** [comment]
Why are you trying to create template from transparency data? That doesn't make any sense.

**Comment by edolo595** [comment]
I think I got confused.
could you give me an example how to create templates in cache please

**Comment by robertvazan** [comment]
Read the tutorial carefully. It gives you a working example of how to persist templates as byte[].

https://sourceafis.machinezoo.com/java
