### ISSUE TITLE
FingerprintTemplate Format

### ISSUE THREAD

**Issue by sergioluc** [robertvazan/sourceafis-java#23]
Hi..
I want to store the fingerprint template in database,  I used Cassandra database and set the data type of the fingerprint template as BLOB. But it didn't worked.
 So, could you tell me which data type should I use if I want to store the fingerprint template into a database? 
Thanks!!!

**Comment by robertvazan** [comment]
Database integration is currently out of scope for SourceAFIS. Since BLOB type reliably stores arbitrary byte arrays, I can only assume you are using either the database or SourceAFIS incorrectly. You will have to debug your code. Let me know if anything is poorly documented in SourceAFIS docs.
