### ISSUE TITLE
Getting Unsupported image format while passing byte array to FingerprintTemplate

### ISSUE THREAD

**Issue by nasaab** [robertvazan/sourceafis-java#27]
I have trying to pass byte array to FingerprintTemplate 

public Boolean compareFingerPrint() throws IOException {
		String encoded_string = "Wn8OG3B4lIoFT5y+vc8FGsezEmrKPDQVZgtkZFs0emNKtLkQiOsoXE5xGsEJ9hnUk129j7Jgg4uWlMXvAn+f0y0owwuRGyvkp+EomVvdmWgZ2iiHXMwyEi3AtCwnSrryP7eCAHRJQRiEXXBS757qbgftJ0Etd1tBGi1yh/cdpVwbLcnrrw1fYCpk/0fwbPl8Gy3J668NX2AqZP9H8Gz5fBstyeuvDV9gKmT/R/Bs+XwbLcnrrw1fYCpk/0fwbPl8Gy3J668NX2AqZP9H8Gz5fBstyeuvDV9gKmT/R/Bs+XwbLcnrrw1fYCpk/0fwbPl8Gy3J668NX2AqZP9H8Gz5fBstyeuvDV9gKmT/R/Bs+XwbLcnrrw1fYCpk/0fwbPl8Gy3J668NX2AqZP9H8Gz5fBstyeuvDV9gKmT/R/Bs+XwbLcnrrw1fYCpk/0fwbPl8Gy3J668NX2AqZP9H8Gz5fBstyeuvDV9gKmT/R/Bs+XwbLcnrrw1fYCpk/0fwbPl8Gy3J668NX2AqZP9H8Gz5fA==";
		
		double threshold = 40;
		boolean matches;
		
//		byte[] probeImage = Files.readAllBytes(Paths.get("/tmp/left_index/demo1.png"));
//		byte[] candidateImage = Files.readAllBytes(Paths.get("/tmp/left_index/demo1.png"));
		
		
		
		byte[] probeImage = Base64.decodeBase64(encoded_string.getBytes());
		byte[] candidateImage = Base64.decodeBase64(encoded_string.getBytes());
		
		System.out.println("Probe Image : " + Arrays.toString(probeImage));

		FingerprintTemplate probe = new FingerprintTemplate(
		    new FingerprintImage()
		        .dpi(500)
		        .decode(probeImage));

		FingerprintTemplate candidate = new FingerprintTemplate(
		    new FingerprintImage().dpi(500)
		        .decode(candidateImage));
		
		double score = new FingerprintMatcher()
			    .index(probe)
			    .match(candidate);
		
		System.out.println("Score : " + score);
		
		if(score >= threshold)
			matches = true;
		else 
			matches = false;
		
		return matches;
	}

**Comment by robertvazan** [comment]
That BASE64 string is too short to be an image. It also contains some repetitive content. This is definitely not an image. SourceAFIS is right to reject it.

**Comment by nasaab** [comment]
Actually that BASE64 is encoded byte array of scanned finger data which i'm
getting from front-end side, and when i decode on my backend side and
passed that decoded byte array to FingerprintTemplate i come up with those
exception.

**Comment by robertvazan** [comment]
Do you want to say that this is a template produced by SourceAFIS? I find it unlikely that SourceAFIS would produce the repetitive pattern. Can you post the code that generated the data?
