### ISSUE TITLE
compile an example with android

### ISSUE THREAD

**Issue by gbelmm** [robertvazan/sourceafis-java#3]
Why would this error be when trying to compile an example with android?
![captura de pantalla 2018-02-08 a la s 12 53 55](https://user-images.githubusercontent.com/731936/35982693-2f0d1674-0ccf-11e8-8f39-806cda224313.png)

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.example.gabrielmunoz.digitalpersona"
        minSdkVersion 14
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
 
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.android.support:design:26.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    compile 'asia.kanopi.tools:fingerscan:0.1'
    compile 'com.machinezoo.sourceafis:sourceafis:2.2.0'

}
`

**Comment by gbelmm** [comment]
fix me

in the project gradle.properties, add:
android.enableD8=true

**Comment by robertvazan** [comment]
Seems resolved then.
