### ISSUE TITLE
Building fingerprint template for serialized templates in version 3.10.0 causes crash. why?

### ISSUE THREAD

**Issue by asr1994** [robertvazan/sourceafis-java#30]
Hi Robert, thanks for this great library. I'm facing with new issue today. Actually I've upgraded my library from version **3.8.1** to **3.10.0** and now i'm experiencing **crashes** on building templates for 
**serialized template** stored in my **local DB**.
I'll be appreciated if you guide me.

Thanks

**Comment by robertvazan** [comment]
Those are not crashes. They are exceptions. Template format has changed. When upgrading SourceAFIS to new major/minor version, always reextract all templates from original images.
