### ISSUE TITLE
Fingerprint Template Format Issue

### ISSUE THREAD

**Issue by YazanZ** [robertvazan/sourceafis-java#31]
In my JavaFX project I added all necessary .jar files and trying to generate template using the sample images downloaded from NIST and using the following code :

> try {
            byte[] image = Files.readAllBytes(path);
            FingerprintTemplate template = new FingerprintTemplate(
                    new FingerprintImage()
                            .dpi(500)
                            .decode(image));
            byte[] serialized = template.toByteArray();
            System.out.println(serialized.toString());
        }
        catch(IOException e) {
        }

The printed result is : **[B@3ea9107**, 
I think this is wrong because as I read the result should be a long hash !

**Comment by robertvazan** [comment]
Serialized template is not a hash. It's a byte array. Method `println` will print only an ID of the byte array. Write it to a file and open it in binary editor (or specialized CBOR viewer) to see what's inside.

**Comment by YazanZ** [comment]
I want to store fingerprint template in the database, Should I store **serialized** array or what?

**Comment by robertvazan** [comment]
You should store the byte array returned by `FingerprintTemplate.toByteArray()`.
