### ISSUE TITLE
First instance of the FingerprintTemplate takes the rest not

### ISSUE THREAD

**Issue by dan-developer** [robertvazan/sourceafis-java#33]
![image](https://user-images.githubusercontent.com/10473169/81887955-b1ce7a80-9576-11ea-9492-8df347d8d14d.png)

Time elapsed: 0
Time elapsed: 805
Time elapsed: 820
Time elapsed: 913

The first time you start FingerprintTemplate it takes 0.805 seconds.
Then in the loop it takes 0.1 seconds.
Why does it happen? Is it a problem in JAVA?

**Comment by robertvazan** [comment]
This is normal behavior of Java. The code is not compiled yet the first time around.

**Comment by dan-developer** [comment]
I am producing a jar file, is this behavior the same for this type of file too? Sorry about that, I know you're a busy person, but I'm trying to help improve the project.

**Comment by robertvazan** [comment]
That's a general Java question unrelated to SourceAFIS. And the answer is not simple. Java warmup depends on many variables and there are several ways to improve it. I don't have any direct links, sorry. You will have to read up on the subject.
