### ISSUE TITLE
Android API 19 not supported

### ISSUE THREAD

**Issue by mkoakintomiwa** [robertvazan/sourceafis-java#34]
Please help, I am using an android KitKat (API 19) biometric device with sourceafis, but I keep getting errors. I later learnt that in require min-api 24. Please how can I use sourceafis with API 19.

**Comment by robertvazan** [comment]
There's no way to run SourceAFIS on Android API 19 without substantial changes to the code. SourceAFIS mainline will remain on API level 24 until the market catches up, which will happen in about 2 years. Meantime I recommend sacrificing some market share for your app.

**Comment by mkoakintomiwa** [comment]
So there is nothing you can do for me personally. May be a previous version sourceafis. Please I'm desperately in need of it. I have done alot to get bitmap images from the device just to use sourceafis only to find out its min-api is 24.

**Comment by robertvazan** [comment]
Older versions of SourceAFIS do not run on Android at all. You would have to backport the library yourself. Or pay me to do it for you if this is a commercial project. Request a quote via email if that is the case.

**Comment by robertvazan** [comment]
BTW, check the performance of the target device(s). If Android version is so old, chances are the CPU will be too slow to run SourceAFIS. SourceAFIS feature extractor takes 50ms to process one image on desktop CPU. It may need more than one second of time on mobile devices.

**Comment by mkoakintomiwa** [comment]
Okay, how about using .net framework with sourceafis.

**Comment by robertvazan** [comment]
That would not work on Android either. The last version of the .NET port targets desktop .NET Framework.

**Comment by mkoakintomiwa** [comment]
How fast is it?

**Comment by robertvazan** [comment]
Slower than the Java port AFAIK.

**Comment by mkoakintomiwa** [comment]
Alright, I am thinking of generating the images from the device and doing
the matching process on desktop. But I would love to use Python instead of
C# and .NET framework.

**Comment by robertvazan** [comment]
SourceAFIS has an older C#/.NET port that will work. Python port does not exist.

**Comment by mkoakintomiwa** [comment]
Okay, I will go with that, thanks for your time.

**Comment by mkoakintomiwa** [comment]
Please give me the link of the documentation of sourceafis .NET

**Comment by robertvazan** [comment]
https://github.com/robertvazan/sourceafis-net
