### ISSUE TITLE
Expose minutiae details

### ISSUE THREAD

**Issue by saroehr** [robertvazan/sourceafis-java#35]
Would it be possible to expose the "minutiae" information in some meaningful way on the FingerprintTemplate? We have a need to render minutiae information as an overlay onto the fingerprint image itself. It appears this information is inside the Immutable object, but that object is unvailable for reading data from. Perhaps some form of the minutiae information could be exposed externally to a caller or available via subclass?

**Comment by robertvazan** [comment]
You can parse the serialized template:

https://sourceafis.machinezoo.com/template

There is also a library that does the parsing for you (undocumented at the moment):

https://github.com/robertvazan/sourceafis-transparency-java

And there's even a library that does the visualization for you (undocumented too):

https://github.com/robertvazan/sourceafis-visualization-java

**Comment by saroehr** [comment]
Hi Robert!

Yes we are parsing the serialized template but this is a large amount of overhead to get this information it seems as we first must deserialize the template from the image to then serialize it and then then deserialize it again to parse the information from the immutable that contains it. This seems unnecessary and makes the dependent upon knowing the serialized form which is subject to changes as you mention.

Thank you for your reply. I inherited this code and if there is a better way to do this that is great! I will review the transparency topic more to see if I can figure out why it isn’t providing everything the developer needed.

Thanks!

Scott
________________________________

**Comment by robertvazan** [comment]
Template serialization/deserialization is fast, especially with the new CBOR format. Only feature extraction is expensive.

**Comment by saroehr** [comment]
That is good to know that the serialization is fast. But we still have to turn around and re-read it back from the serialized template.. Is there a reason that the template information could not be exposed to avoid that second round trip step? It also makes our code brittle if the template form changes we have to update our code that re-reads it. Exposing the details via the API would shield us from that without breaking the functions if the exposed object is read-only.

**Comment by saroehr** [comment]
Perhaps the need is moot also if I can figure out how to get the information they appear to be desiring from the transparency.

**Comment by saroehr** [comment]
Thank you man.

**Comment by robertvazan** [comment]
Even API of the transparency library is subject to change with every release. There's a roadmap for stable API for minutia access/editing, so this might be available in the future.

**Comment by sifislaz** [comment]
Hello @saroehr ,
Have you figured out a way to use the SourceAFIS Transparency in order to expose the minutiae points? Because I can't figure out how to use it.
Thank you in advance.
