### ISSUE TITLE
Different scores when interchanging probe and candidate for matching (color fingerprint photos)

### ISSUE THREAD

**Issue by valerietram88** [robertvazan/sourceafis-java#41]
Hi,

First of all, thank you very much for your sharing a such project. 

But I find out a problem when I try to match 2 fingerprint images (in color) (A and B) and A.match(B) != B.match(A). You can in see the below photos. I try different color fingerprint photo couples, the problem still remains. I don't meet this problem when doing the same experiments with gray images.

I wonder if SourceAFIS does not support images in color. May you help me clear this point please!

Thank you in advance!

![image](https://user-images.githubusercontent.com/68628367/117394251-ac1a2500-aeaa-11eb-8cc7-abc480bd9121.png)
![image](https://user-images.githubusercontent.com/68628367/117394253-acb2bb80-aeaa-11eb-995c-c25a228f8e0e.png)

**Comment by robertvazan** [comment]
The algorithm is not symmetrical. This is expected behavior. Errors are only meaningful when measured on large enough dataset. See current accuracy benchmarks:

https://sourceafis.machinezoo.com/cli
