### ISSUE TITLE
Do we really need to check pixel buffer size?

### ISSUE THREAD

**Issue by AlekseyMalyshev** [robertvazan/sourceafis-java#42]
`FingerprintImage` constructor throws an exception if `pixels.Length != width * height` I think this it pointless because I may reuse the buffer for multiple images and the size does not have to match. With this check it is not possible to reuse the buffer.

```
        public FingerprintImage(int width, int height, byte[] pixels, FingerprintImageOptions options = null)
        {
            if (pixels == null)
                throw new ArgumentNullException(nameof(pixels));
            if (width <= 0 || height <= 0 || pixels.Length != width * height)
                throw new ArgumentOutOfRangeException();
            Matrix = new DoubleMatrix(width, height);
            for (int y = 0; y < height; ++y)
                for (int x = 0; x < width; ++x)
                    Matrix[x, y] = 1 - pixels[y * width + x] / 255.0;
            if (options == null)
                options = new FingerprintImageOptions();
            Dpi = options.Dpi;
        }
```

**Comment by robertvazan** [comment]
@AlekseyMalyshev Reusing the buffer is a pointless optimization, because feature extractor is insanely expensive compared to array copy. Having additional consistency check is more valuable than shaving microseconds from 50ms operation. Just create new array of the correct length.
