### ISSUE TITLE
When I try and build the code in netbeans I get the following error

### ISSUE THREAD

**Issue by Azac24** [robertvazan/sourceafis-java#46]
Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.2.0:jar (attach-javadocs) on project sourceafis: MavenReportException: Error while generating Javadoc: Project contains Javadoc Warnings -> [Help 1]

I'm not sure what I'm doing wrong, but I used git-clone to download the files.

**Comment by robertvazan** [comment]
Probably a version of JDK that issues different warnings than the one used for regular builds. Can you post the warning here?

**Comment by Azac24** [comment]
Error fetching link: C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\javadoc-bundle-options. Ignored it.
No previous run data found, generating javadoc.
Javadoc Warnings
Loading source files for package com.machinezoo.sourceafis...
Constructing Javadoc information...
Building index for all the packages and classes...
Standard Doclet version 17.0.1+12-LTS-39
Building tree for all the packages and classes...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\com\machinezoo\sourceafis\FingerprintCompatibility.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\com\machinezoo\sourceafis\FingerprintImage.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\com\machinezoo\sourceafis\FingerprintImageOptions.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\com\machinezoo\sourceafis\FingerprintMatcher.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\com\machinezoo\sourceafis\FingerprintTemplate.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\com\machinezoo\sourceafis\FingerprintTransparency.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\com\machinezoo\sourceafis\package-summary.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\com\machinezoo\sourceafis\package-tree.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\com\machinezoo\sourceafis\class-use\FingerprintCompatibility.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\com\machinezoo\sourceafis\class-use\FingerprintImage.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\com\machinezoo\sourceafis\class-use\FingerprintImageOptions.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\com\machinezoo\sourceafis\class-use\FingerprintMatcher.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\com\machinezoo\sourceafis\class-use\FingerprintTemplate.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\com\machinezoo\sourceafis\class-use\FingerprintTransparency.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\com\machinezoo\sourceafis\package-use.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\overview-tree.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\deprecated-list.html...
Building index for all classes...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\allclasses-index.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\allpackages-index.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\index-all.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\index.html...
Generating C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\apidocs\help-doc.html...

That is what it is showing me. My java SDK is 17.0.1. Should I use an older version?

**Comment by robertvazan** [comment]
The warning is not visible in this log, so I have no idea what to fix. I am still on Java 16/11/8. I should probably add CI builds for all Java versions.

**Comment by robertvazan** [comment]
Short term fix for you is to remove "<failOnWarnings>true</failOnWarnings>" from pom.xml.

**Comment by robertvazan** [comment]
Javadoc warnings-as-errors are now enabled only in CI builds. Pull latest version. It should build without errors.

**Comment by Azac24** [comment]
So I'm still getting the same error. I've gone through the entire log and here is everything in red/yellow. I have also changed my jdk to 15.0.2 hoping that would help, but nothing. I would also like to say I find it impressive how quickly you responded and I really do appreciate your help.
Yellow: 
--- maven-surefire-plugin:2.22.2:test (default-test) @ sourceafis ---
file.encoding cannot be set as system property, use <argLine>-Dfile.encoding=...</argLine> instead

Red: 
--- maven-javadoc-plugin:3.2.0:jar (attach-javadocs) @ sourceafis ---
Error fetching link: C:\Users\Azac2\OneDrive\Documents\Wright State University\CEG-4110\Project\sourceafis-java\target\javadoc-bundle-options. Ignored it.

Failed to execute goal org.apache.maven.plugins:maven-gpg-plugin:1.6:sign (sign-artifacts) on project sourceafis: Unable to execute gpg command: Error while executing process. Cannot run program "gpg.exe": CreateProcess error=2, The system cannot find the file specified -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by robertvazan** [comment]
Try with ` -Dgpg.skip=true` option. I will try to find more permanent solution later.

**Comment by robertvazan** [comment]
@Azac24 Could you post the command you are using to run the build?

**Comment by Azac24** [comment]
So the first time I tried to run the build I opened the project with NetBeans and hit build. I was just testing to make sure everything was working before I constructed my main. That's where I was getting the errors.

**Comment by Azac24** [comment]
It works now. I just wasn't familiar enough with Maven and wasn't structuring my main correctly. Thank you so much for your help, Its running correctly after I added a main method in. Thanks again for your help and for getting back to me so quickly!

BUILD SUCCESS
------------------------------------------------------------------------
Total time:  3.324 s
Finished at: 2021-11-08T16:42:17-05:00
