### ISSUE TITLE
Sample code to enroll and match two fingerprints

### ISSUE THREAD

**Issue by girma-ai** [robertvazan/sourceafis-java#48]
Thank you robertvazan, for your wonderful open source project. Please could you give me a sample code to enroll and match two fingerprint?

**Comment by robertvazan** [comment]
Doesn't the tutorial describe what you want exactly?

https://sourceafis.machinezoo.com/java

**Comment by girma-ai** [comment]
The tutorial is so descriptive. But i want to enroll two fingers at the same time.

**Comment by robertvazan** [comment]
Do you mean two-finger matching? There's no prescribed way to do that, but adding up scores of the two fingers is a reasonable way to do two-finger matching.

**Comment by girma-ai** [comment]
Yes, two-finger matching.Thank you for your immediate response.I will try
it and let you know
Thanks in advance!!
