### ISSUE TITLE
Unsupport image format

### ISSUE THREAD

**Issue by nesux** [robertvazan/sourceafis-java#5]
Hi Robert，Is possible to support other format of finger print image, now only i have tif or bmp file image, i can't conver the tif filw to raw image,do you have any suggestion? thank you.
Exception in thread "main" java.lang.IllegalArgumentException: Unsupported image format
	at com.machinezoo.sourceafis.TemplateBuilder.readImage(TemplateBuilder.java:136)
	at com.machinezoo.sourceafis.TemplateBuilder.extract(TemplateBuilder.java:19)
	at com.machinezoo.sourceafis.FingerprintTemplate.create(FingerprintTemplate.java:92)

**Comment by imrankst1221** [comment]
@robertvazan thanks for your awesome library. 
I also get "Unsupported image format" error. By in my case, I try **PNG, JPEG, bitmap** and convert it into the byte array,  but always got the error. I am using **FM220** fingerprint which returns Bitmap and ISO_Template byte array. I try almost every way but not working.

**Comment by robertvazan** [comment]
@imrankst1221 Make sure you are using latest SourceAFIS. Image decoding currently doesn't work on Android. It must be a desktop JRE. If it's headless JRE, try full JRE. Make sure the image can be opened in image viewer. Turn on slf4j logging and see what errors are logged when SourceAFIS tries to decode the image.

**Comment by kdiawara96** [comment]
Erreur lors de la création du template pour probeImage.
      
>      java.lang.IllegalArgumentException: Unsupported image format [ImageIO = 'java.lang.UnsupportedOperationException: Image decoder is not available.', WSQ = 'java.lang.IllegalArgumentException: This is not a WSQ image.', Android = 'java.lang.NoClassDefFoundError: Failed resolution of: Lcom/machinezoo/noexception/Exceptions; -> java.lang.ClassNotFoundException: Didn't find class "com.machinezoo.noexception.Exceptions" on path: DexPathList[[zip file "/data/app/~~Ar2qCV_DK-z6YbvZ9j2OCA==/com.futronictech-ysDXwwqC4YxxZht6daeceQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~Ar2qCV_DK-z6YbvZ9j2OCA==/com.futronictech-ysDXwwqC4YxxZht6daeceQ==/lib/arm64, /data/app/~~Ar2qCV_DK-z6YbvZ9j2OCA==/com.futronictech-ysDXwwqC4YxxZht6daeceQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]'].


code :
  byte[] pngBytes = convertToPNG(probeImage);

      FingerprintTemplate probeTemplate = null;
            try {
           
                FingerprintImage fingerprintImage = new FingerprintImage(pngBytes);
                probeTemplate = new FingerprintTemplate(fingerprintImage);
          
            } catch (Exception e) {
          
                return false;
            }

method:

public static byte[] convertToPNG(byte[] rawBytes) throws IOException {
    Bitmap bitmap = BitmapFactory.decodeByteArray(rawBytes, 0, rawBytes.length);
    ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
    bitmap.compress(Bitmap.CompressFormat.PNG, 100, outputStream);
    return outputStream.toByteArray();
}

please help me @robertvazan

**Comment by robertvazan** [comment]
@kdiawara96 Recursive dependencies are missing. Did you use Gradle to manage dependencies or did you just copy SourceAFIS JAR into your project?

**Comment by kdiawara96** [comment]
Hi Robert,

Thank you for your response.

I uploaded the SourceAFIS project to GitHub and generated the JAR file
using Maven before adding it to my Android project. On the website, I only
found the Maven dependency, but I couldn’t find a Gradle dependency, so I
clicked the Maven button to proceed.

Could you confirm if there is a proper Gradle configuration available for
SourceAFIS, or if this approach might have caused the missing recursive
dependencies issue? Also, is there a recommended way to ensure all
dependencies are properly included when integrating the SDK into an Android
project?

Thank you for your help.

Kind regards,
Karim



Le mar. 10 déc. 2024 à 18:30, Robert Važan ***@***.***> a
écrit :

**Comment by robertvazan** [comment]
@kdiawara96 Go to [SourceAFIS for Java](https://sourceafis.machinezoo.com/java) page. In the download section, you can select one of several tools. Gradle is the second one in the list. Do you see it? It currently produces this Gradle configuration line:

```
implementation 'com.machinezoo.sourceafis:sourceafis:3.18.1'
```

**Comment by kdiawara96** [comment]
Hi Robert,

Thank you for pointing this out.

I did try clicking the Gradle button on the SourceAFIS page, but it didn’t
work as expected at the time. This is why I decided to retrieve the code
from GitHub and generate the JAR file manually using Maven.

I’ll try adding the Gradle configuration directly as you suggested and see
if it resolves the issue.

Thank you for your assistance!

I’ve attached a screenshot showing the issue I encountered while trying to
use the Gradle button.

Kind regards,



Le mar. 10 déc. 2024 à 22:58, Robert Važan ***@***.***> a
écrit :

**Comment by kdiawara96** [comment]
Hi Robert,

I followed your suggestion to add the dependency via Gradle instead of
using the JAR file. I removed the JAR file from the libs folder and added
the following line to my Gradle configuration:

gradle

implementation 'com.machinezoo.sourceafis:sourceafis:3.18.1'

However, after syncing the project, I encountered an issue where classes
like FingerprintMatcher cannot be resolved in the code. I also cleaned and
rebuilt the project to ensure there were no residual issues, but the
problem persists.

Additionally, I verified that Maven Central is included in the repositories
section of my Gradle file. The dependency seems to download correctly, but
the classes are still not accessible in the project.

Would you happen to know what could be causing this? Do you think there
might be additional steps or configurations I need to apply for the
integration to work?

Thank you again for your guidance!

Kind regards,



Le mer. 11 déc. 2024 à 09:56, Karim Diawara ***@***.***> a
écrit :

**Comment by robertvazan** [comment]
@kdiawara96 Android API version?

**Comment by robertvazan** [comment]
@kdiawara96 Downgrade to the last version tested on Android (3.14.2)?

**Comment by kdiawara96** [comment]
I followed your suggestion to downgrade to version 3.14.2 of SourceAFIS.
However, I am still encountering issues when trying to use the library in
my Android project. Specifically, the error I get is:
"Cannot resolve symbol 'FingerprintImage'"

Here’s what I’ve done so far:

   - Updated my build.gradle file with the dependency:

   implementation 'com.machinezoo.sourceafis:sourceafis:3.14.2'


Despite this, classes like FingerprintImage and FingerprintMatcher still
cannot be resolved in my code.

Thank you for your time and assistance!



Le mer. 11 déc. 2024 à 11:18, Robert Važan ***@***.***> a
écrit :

**Comment by robertvazan** [comment]
@kdiawara96 Android API level?

**Comment by kdiawara96** [comment]
I have already updated the minSdkVersion to 24, as SourceAFIS requires at
least API level 24. Despite this, I am still encountering the same issue
where the FingerprintImage class cannot be resolved. The error persists
even after making this change, and I am unable to use the library correctly.

Here’s a quick summary of what I’ve done so far:

   - I’ve updated the minSdkVersion to 24 in my build.gradle file.
   - I’ve also ensured that I am using SourceAFIS version 3.14.2, which you
   recommended.
   - Gradle has synced successfully, and all dependencies seem to be in
   place.
   - However, the FingerprintImage and other SourceAFIS classes (like
   FingerprintMatcher) still cannot be resolved in my code.




Le mer. 11 déc. 2024 à 11:33, Robert Važan ***@***.***> a
écrit :

**Comment by robertvazan** [comment]
@kdiawara96 I ran out of ideas. There's nothing special about SourceAFIS library. It's puzzling that other libraries (presumably) work while SourceAFIS doesn't. This will require some serious debugging effort on your side.

**Comment by kdiawara96** [comment]
Thank you for your continued support.

I understand your point, and I will start debugging the issue more thoroughly on my end. Given that other libraries seem to work fine while SourceAFIS doesn't, I will investigate any possible configuration or compatibility issues more closely.

I appreciate all your help so far, and I will keep you updated on my progress. If I find any specific issues or need further guidance, I will reach out again.

Thanks again for your time and assistance!
