### ISSUE TITLE
Java Android - Error during APK Build

### ISSUE THREAD

**Issue by innotechdev-olufemi** [robertvazan/sourceafis-java#50]
Kindly help, I get this error during APK guild, the app works fine during debug run.
I have updated gradle to  version 7.4 and Android Gradle Plugin Version to 7.3.0-alpha03

One or more instruction is preventing default interface method from being desugared: java.lang.Double it.unimi.dsi.fastutil.objects.Reference2DoubleMap.getOrDefault(java.lang.Object, java.lang.Double)

**Comment by robertvazan** [comment]
Android API level?

**Comment by innotechdev-olufemi** [comment]
Android API 31

**Comment by innotechdev-olufemi** [comment]
Android API 31

**Comment by innotechdev-olufemi** [comment]
Issue resolved
I modified the App gradle as this

compileOptions {
        coreLibraryDesugaringEnabled true

        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }


And added the dependency 
coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.5'

**Comment by robertvazan** [comment]
I am wondering whether `desugar_jdk_libs` is really needed. Also, latest SourceAFIS targets Java 11.
