### ISSUE TITLE
Not getting score above 10 by using FingerprintMatcher

### ISSUE THREAD

**Issue by rajtts009** [robertvazan/sourceafis-java#51]
Hello,
Im using FingerprintMatcher to get the score >40. but im not able to get.
Please suggest me any solution.  

This is my sample code:
ByteArrayOutputStream stream = new ByteArrayOutputStream();
                    Bitmap bitmap = PictureUtility.drawableToBitmap(imgCapture.getDrawable());
					bitmap.compress(Bitmap.CompressFormat.JPEG, 100, stream);					 
                    FingerprintTemplate probe = new FingerprintTemplate().create(stream.toByteArray()).dpi(500);
                    

                    Bitmap bitmap1 = ((BitmapDrawable) fingerPrintView.getDrawable()).getBitmap();
					showAlert("bitmap1", "databseImage " + probe);
					//Bitmap bitmap1 = ((
					ByteArrayOutputStream stream1 = new ByteArrayOutputStream();
					bitmap1.compress(Bitmap.CompressFormat.JPEG, 100, stream1);
					FingerprintTemplate candidate = new FingerprintTemplate().create(stream1.toByteArray()).dpi(500);
					showAlert("bitmap1", "databseImage " + candidate);
					System.out.println("candidate++ " + Arrays.toString(candidate.toByteArray()));
					double score = new FingerprintMatcher()
							.index(probe)
							.match(candidate);

Hex form tamplate data:

hexDataprobe 1F8B08000000000000008D56CB6E1C3710FC97392F887E37B9BF12E4605B8AB58728812227310CFDBB6B34DCC4216706810E02A4656D77D7A3FBDBF2F478FBFCF4BA5C8DE8B2FC7A7BFEF27AFBF0B85C7FFAB63CDC5E1E3FBDDE7E7B5EAE52AA13AB576FCCDC24ECB2BC7EFD1D9F5B3EDE7EF9F2F2E9C3FBE72ECBDFCB35EB65F9BA5C3DDE2EFFC1E042CEE1242C6E5553EB3186B5770C69348078A9DC5C335AE5AC790291B641581D20B488B1042B05556AEEC7184CBD0E9309C419D0DA4C8CC44E41B857A223089556259B26FE65A9D24E408436101E41BC2891367614A3229EFF96F2F8FC707BFEDC016C03501AE761C543AD3552C974907BD28BD046AEE4C8AE9748CCA1A9A123D2CCDD2A94DF9FB3B4491C0E6CC5309852C0F009B3DA47913E91C2C60E753A94DA80B55BC3FAE7F5798C354831E3682DABD624B716FB93D4D826C93C033000A43537AD149C274D6CCA8A918D28A45528C28C5C52E44C135B273A72114514520878D53C817482D19BA9B33669B7FBDA9B4F9B9A0F8E6C516150C52F3F98DE5DC831564DC58D0CEE26128CBF9AEC03786E1AF2B96431037B110A7FD7303E6BBC3722338A8954D7B6468434A37D25736CC387AF26298750BA813BE41D5C79960D7E4FA9711A0818115A5D4989C8F4133F086D23659A23F7B0941F7BB903C8A4022E19E0936B5D059999B60FC0D2C365AC4060C9E4449FC8FBA0FFE16A1A6D49055E720A640A43F2612731195B1D48C1D99A014DA212283EE447562710EF213571729C71334617E9A4F2285C1564841BAC82ED71B67D7A2193D7AC90A8054A11E44D95BA6FD59EF85356736994A0051D72E510DD7FCFD6A73985941487281DE3D474D83EF44CE23DA5681497A10CD8D5607B74E3473EEB45B4F139A4053DC019480B4C1379BB0FD0EF11ACD849586CB5D6D62C831A92E36CF3FD13173A89222187707C3FDA4176ED2F1DEF4318D5EDA5593893D5CC86DC3913F78631E59E23B1A01517FCAC06D91783F72364272392A0A5B67E7D2077E364087DFBEB9879B4DE100AAE82AD31D29F0FC27F03E0E9AE83A24062E0BC44DC809083DD0DF71EDC1F5A3223B07A4068253E4A6DBF9F51A3A44F627F6777F0FEF2A6521B4688EB057266356DFB71295BEAF34EDEAA382E5B380A71858B6C9F4CD13B9BB31612CF0C291A10431EBCEFB7B1CE29B94652544C11C9B0CAE28085FEF53E9F71CD7158C3918A8891D30B88B373D1464B618C469864AC4B1CAAF20335B5AEA6D4B79F2FCB9F8F2F7FBC3F5FA0057CE2AFDBC3EBD35A64BC7D07171D6ACEE60C0000

hexDataCandidate:

hexDatacandidate 1F8B08000000000000008D56CB6E1C3710FC97392F887E37B9BF12E4605B8AB58728812227310CFDBB6B34DCC4216706810E02A4656D77D7A3FBDBF2F478FBFCF4BA5C8DE8B2FC7A7BFEF27AFBF0B85C7FFAB63CDC5E1E3FBDDE7E7B5EAE52AA13AB576FCCDC24ECB2BC7EFD1D9F5B3EDE7EF9F2F2E9C3FBE72ECBDFCB35EB65F9BA5C3DDE2EFFC1E042CEE1242C6E5553EB3186B5770C69348078A9DC5C335AE5AC790291B641581D20B488B1042B05556AEEC7184CBD0E9309C419D0DA4C8CC44E41B857A223089556259B26FE65A9D24E408436101E41BC2891367614A3229EFF96F2F8FC707BFEDC016C03501AE761C543AD3552C974907BD28BD046AEE4C8AE9748CCA1A9A123D2CCDD2A94DF9FB3B4491C0E6CC5309852C0F009B3DA47913E91C2C60E753A94DA80B55BC3FAE7F5798C354831E3682DABD624B716FB93D4D826C93C033000A43537AD149C274D6CCA8A918D28A45528C28C5C52E44C135B273A72114514520878D53C817482D19BA9B33669B7FBDA9B4F9B9A0F8E6C516150C52F3F98DE5DC831564DC58D0CEE26128CBF9AEC03786E1AF2B96431037B110A7FD7303E6BBC3722338A8954D7B6468434A37D25736CC387AF26298750BA813BE41D5C79960D7E4FA9711A0818115A5D4989C8F4133F086D23659A23F7B0941F7BB903C8A4022E19E0936B5D059999B60FC0D2C365AC4060C9E4449FC8FBA0FFE16A1A6D49055E720A640A43F2612731195B1D48C1D99A014DA212283EE447562710EF213571729C71334617E9A4F2285C1564841BAC82ED71B67D7A2193D7AC90A8054A11E44D95BA6FD59EF85356736994A0051D72E510DD7FCFD6A73985941487281DE3D474D83EF44CE23DA5681497A10CD8D5607B74E3473EEB45B4F139A4053DC019480B4C1379BB0FD0EF11ACD849586CB5D6D62C831A92E36CF3FD13173A89222187707C3FDA4176ED2F1DEF4318D5EDA5593893D5CC86DC3913F78631E59E23B1A01517FCAC06D91783F72364272392A0A5B67E7D2077E364087DFBEB9879B4DE100AAE82AD31D29F0FC27F03E0E9AE83A24062E0BC44DC809083DD0DF71EDC1F5A3223B07A4068253E4A6DBF9F51A3A44F627F6777F0FEF2A6521B4688EB057266356DFB71295BEAF34EDEAA382E5B380A71858B6C9F4CD13B9BB31612CF0C291A10431EBCEFB7B1CE29B94652544C11C9B0CAE28085FEF53E9F71CD7158C3918A8891D30B88B373D1464B618C469864AC4B1CAAF20335B5AEA6D4B79F2FCB9F8F2F7FBC3F5FA0057CE2AFDBC3EBD35A64BC7D07171D6ACEE60C0000

**Comment by robertvazan** [comment]
I don't see the cause, but I have a few hints:

* You are using deprecated APIs. Upgrade and use current APIs.
* Save the images in files and compare them visually. Should they match?
* Check DPI. It must be the real sensor DPI.

I cannot recognize format of the two files you posted.

**Comment by rajtts009** [comment]
Hello,
I'm checking what you have suggested.

*1. Check DPI. It must be the real sensor DPI*
                Here, what is it mean "real sensor DPI"

*2. I cannot recognize format of the two files you posted.*
                Here, i posted the template data (probe & candidate) in
HexString.bufferToHex(probe.toByteArray()) format

Thank's,
Raj.

**Comment by robertvazan** [comment]
That's not a CBOR-encoded template. Something is wrong with it. What's `HexString.bufferToHex`? Please upgrade to the latest version of SourceAFIS..
