### ISSUE TITLE
SourceAFIS 3.16.1 Error

### ISSUE THREAD

**Issue by kyalok** [robertvazan/sourceafis-java#54]
Dear Robert 
what could be the couse of this error in gridle implemention of this

implementation 'com.machinezoo.sourceafis:sourceafis:3.15.0'

am getting the error below

![image](https://user-images.githubusercontent.com/36716982/174478780-5b93817b-1ab2-4098-a945-bedd216bbcbd.png)

**Comment by robertvazan** [comment]
Last version tested on Android is 3.14.2. Try that one. If it does not work, check whether API level is 24+ and Java version is 11+.
