### ISSUE TITLE
Compress fingerprint in smartcard

### ISSUE THREAD

**Issue by bekoto** [robertvazan/sourceafis-java#56]
Hi!

I'm working on in project where biometric data must be stored in smartcard, that smartcard get only 4k of memory.
I wanna know if this library would be able to compare as compressed fringerprint img of 50x50;
and know to do it.

**Comment by robertvazan** [comment]
SourceAFIS currently requires high quality fingerprints:

https://sourceafis.machinezoo.com/benchmarks

You could store template on the card (created from large image), in which case accurate matching would be possible. See template size here:

https://sourceafis.machinezoo.com/cli

You can use ANSI/ISO templates as well, which are even smaller.

A lot of work is needed to match tiny images. That's an effort too large for one GitHub issue. Closing for that reason.
