### ISSUE TITLE
Compare 2 differents fingerprints with different size from different device

### ISSUE THREAD

**Issue by bekoto** [robertvazan/sourceafis-java#57]
Hi!
I implement matching oncard, where enrolment where made from digital persona save as jpeg with 500x500, and the verify must be made with POS device where fingerprint is captured with 300x400.

Match doesn't work but when I enrol user  from POS device, matching works very well.

What to do for this matter?

**Comment by robertvazan** [comment]
You don't mention DPI, which probably means you didn't set it. Importance of correct DPI is already documented in the tutorial:

https://sourceafis.machinezoo.com/java

**Comment by bekoto** [comment]
![Untitled](https://user-images.githubusercontent.com/89358171/179865085-60db5eaa-375a-4ce0-a784-c78da68c4417.png)
here is the screen of image details

**Comment by robertvazan** [comment]
Wrong DPI setting, obviously. Consult sensor documentation and set correct DPI.

**Comment by bekoto** [comment]
which one is wrong. the first or second?

**Comment by robertvazan** [comment]
I cannot possibly know. I just see large scale difference and small  DPI difference. That cannot be right.
