### ISSUE TITLE
Excess ram usages when storing FingerprintTemplate in java hashmap Cache

### ISSUE THREAD

**Issue by SanzarRehman** [robertvazan/sourceafis-java#62]
About 100000 FingerprintTemplate is taking upto 2.5gb of ram . Is this normal ?

**Comment by robertvazan** [comment]
SourceAFIS stores some redundant information in in-memory templates to speed up matching. Current version of SourceAFIS consumes [about 11KB per template](https://sourceafis.machinezoo.com/cli). Larger fingerprints (with more minutiae), JVM settings, and GC overhead could easily push your heap to 2.5GB. This is not ideal, but strictly speaking it's not a bug. It's a performance tradeoff and an opportunity for future optimizations.
