### ISSUE TITLE
Performance issue with android 

### ISSUE THREAD

**Issue by zamirszn** [robertvazan/sourceafis-java#65]
hello  , im using this lib o android and i notice the matching process takes long , is there something im doing wrong heres my code 

```
try{
      if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
        byte[] imageBytes = Files.readAllBytes(Paths.get(dir));
        FingerprintImage fingerprintImage = new FingerprintImage(imageBytes);
        FingerprintTemplate fingerprintTemplate = new FingerprintTemplate(fingerprintImage);
        byte[] serializedTemplate = fingerprintTemplate.toByteArray();
        dbHelper.updateCandidateTemplate(id,serializedTemplate );
        return  true;
      }

    }
```

some times it doesnt create the template and the app doesnt response , when it does it takes long to match

**Comment by robertvazan** [comment]
What's slow, feature extraction or matching?

**Comment by zamirszn** [comment]
the feature extraction

**Comment by robertvazan** [comment]
Feature extraction is single-threaded in current version of SourceAFIS. It takes 50ms on fast desktop. It is understandably slow on Android devices. It also uses a lot of RAM. It's not a bug, it's just a performance limitation of the current implementation.

**Comment by zamirszn** [comment]
yeah , I later figure from reading some of the issues , I saw a port of your lib for android , I'm going to try that to see if it work , thanks alot for your time

**Comment by zamirszn** [comment]
yeah , I later figure from reading some of the issues , I saw a port of your lib for android , I'm going to try that to see if it works , thanks alot for your time
