### ISSUE TITLE
SourceAfis does not work on nist database

### ISSUE THREAD

**Issue by itsoulos** [robertvazan/sourceafis-java#66]
I have the following code in Java
try {
            var options = new FingerprintImageOptions()
                    .dpi(500);
            var probe = new FingerprintTemplate(
                    new FingerprintImage(Files.readAllBytes(Paths.get(image1)),options));
            var candidate = new FingerprintTemplate(
                    new FingerprintImage(Files.readAllBytes(Paths.get(image2)),options));
            var matcher = new FingerprintMatcher(probe);
            double similarity = matcher.match(candidate);
            System.out.println(""+1.0*similarity);
        } catch (IOException e) {
            System.out.println("Exception: "+e);
            throw new RuntimeException(e);
        }

And I want to compare two samples from nist database like this:
 java -jar ~/testafis.jar 00002373_A_roll_01.png 00002373_A_roll_04.png 
The result is always low (below 10.0) what I am doing wrong?

Giannis

**Comment by robertvazan** [comment]
`00002373_A_roll_01.png` and `00002373_A_roll_04.png` are two different fingers. You want to compare with `00002373_B_*_01.png`, `00002373_C_*_01.png`, etc.

**Comment by itsoulos** [comment]
Thanks it works now
